import { PiNuclearPlantLight, PiCity } from "react-icons/pi";
import { GoLaw } from "react-icons/go";
import { RiServiceLine } from "react-icons/ri";
import { GiTeamIdea } from "react-icons/gi";
import { FaRecycle } from "react-icons/fa";

export type NavItem = {
  name: string;
  href?: string;
  children?: Array<{ name: string; href: string }>;
};

export const PHONE_NUMBER = ""; // e.g. "+1-555-123-4567" (set to show Call button)

export const NavItems: NavItem[] = [
  { name: "Home", href: "/" },
  { name: "About us", href: "/about-us" },
  {
    name: "Services",
    href: "/services",
    children: [
      {
        name: "Hazardous waste management",
        href: "/services/hazardous-waste-management",
      },
      {
        name: "Plastic waste management",
        href: "/services/plastic-waste-management",
      },
      {
        name: "Industrial waste management",
        href: "/services/industrial-waste-management",
      },
      {
        name: "Extended producer responsibility",
        href: "/services/extended-producer-responsibility",
      },
      { name: "Circular economy", href: "/services/circular-economy" },
      {
        name: "Organic waste management",
        href: "/services/organic-waste-management",
      },
      {
        name: "E-waste management services",
        href: "/services/e-waste-management",
      },
      {
        name: "Rubber scrap waste management",
        href: "/services/rubber-scrap-waste-management",
      },
      { name: "Wooden scrap buyer", href: "/services/wooden-scrap-buyer" },
      {
        name: "Wooden Pallets scrap buyer",
        href: "/services/wooden-pallets-scrap-buyer",
      },
    ],
  },
  { name: "Blog", href: "/blog" },
  { name: "FAQs", href: "/faqs" },
  { name: "Contact us", href: "/contact-us" },
];

// * Content with image
export const hazardContent = [
  "Waste that is harmful to human health and the environment is classified as hazardous. We are a reliable hazardous waste recycler in Ahmedabad, Gujarat, extending an efficacious treatment process that aligns with your industrial waste handling needs.",
  "SV Green is a GPCB approved hazardous waste recycler in Ahmedabad that has earned the stature of the most trusted, owing to our unparalleled services and a well-trained team.",
  "We take time to understand the requirement of businesses, industrial behemoths and government agencies to cater to their distinctive needs. Furthermore, we take responsibility for your hazardous waste from collection to recycling.",
  "As a Hazardous waste management company in Gujarat, we offer a complete range of environmental services, including waste collection, recycling compliances, EHS inspections, and other internal waste management services.",
  "With our regulatory compliance for hazardous waste, you can rest assured of the safety of humans, infrastructure, and the environment.",
];

export const plasticWasteContent = [
  "According to Central Pollution Control Board, in 2019-20, approximately 34,69,780 TPA of plastic waste was generated by 35 states/UTs of India. The figures are alarming and impose a need for plastic waste management. Hence, we step in as a GPCB a GPCB authorized plastic waste recycler in Gujarat.",
  "At SV Green, environment protection is the motto that leads us to deliver top-notch services. Being a plastic waste management company in Ahmedabad",
  "We formulate customized plans for our clients as we understand the distinctive needs of various industries. Furthermore, as a GPCB approved waste recycler, we adhere to regulatory guidelines, so you get 100% compliance, justified pricing and unparalleled services.",
  "Our plastic waste collection activity is undertaken by a well-trained team of people from marginalised sectors that follow stringent safety protocols to ensure seamless service. Additionally, our plastic waste recycling units comply with PCB guidelines so that you can rely on us for quality and accurate services.",
];

export const industrialWasteContent = [
  "Industrial and manufacturing processes generate tons of waste at every stage. The nature of the waste depends on the type of process governed by strict regulations, for instance, hazardous waste. Hence, as Gujarat's one-stop industrial waste management company, we provide comprehensive and strategic solutions.",
  "Being a GPCB authorized industrial waste recycler, we are your perfect ally for recycling, diversions and other purposeful reuse of your waste. SV Green is a leading industrial scrap buyer in Gujarat to provide all-inclusive waste management and disposal services.",
  "Our expert team understands the chemical, materials, and products with proficient knowledge concerning CPCB & GPCB guidelines. Our industrial waste management services vouch for 100% compliance like no other. Being an industrial waste recycling company , we tend to relieve the hassles of waste management.",
];

export const extendedProducerResponsibility = [
  "Producers are assigned significant financial and/or physical responsibility for the handling or disposing of post-consumer plastic waste under the Extended Producer Responsibility (EPR) policy. SV Green is a leading SBM, and GPCB approved EPR agency in Ahmedabad known for convenient recycling programs for large-scale waste generators. We employ specific recycling and disposal by devising individual plastic-focused strategies for transferring responsibility to the producers.",
];

export const circularEconomy = [
  "Our world economy is only 8.6% circular, wasting 91.4% of everything we are using, according to the Circularity Gap Report 2021. It implies the need for massive adoption of the circular economy model.",
  "Circular Economy takes over conventional linear economy approaches, i.e., take, make and dispose. It ascertains waste reduction by reusing, repairing, refurbishing, and recycling waste materials. We at SV Green are a leading GPCB authorized recycler offering advanced recycling solutions. Not only do we enable businesses to fulfill their responsibility by creating a positive social impact, but we also take concrete steps towards environmental and economic sustainability.",
];

export const organicWaste = [
  "The best quality of organic waste is that it is biodegradable in nature as it originates from living sources like animals, plants, and microorganisms. It is a highly reusable form of waste for energy, recreating sustainable products, manures, and more.",
  "As a major organic waste recycler in Gujarat, we have the most convenient and highly effective processes to treat and manage organic waste. We provide comprehensive organic waste management to businesses for appropriate recycling from collection to processing in our unique facilities. Hence, Recycling Hub is the name you can rely on when it comes to any type of waste management solution.",
];

export const eWaste = [
  "Safe disposal of Electronic waste or E-waste is quintessential. Hence, we step in as a GPCB registered E-waste recycler",
  "E-waste is those electronic products that have come to an end of their estimated effective lifespan. When disposed of in landfills, these products become toxic and hazardous, posing a threat to human health and the environment.",
  "E-waste recycling using appropriate methods enables the recreation of products ensuring minimum waste in landfills. Recycling Hub is a renowned E-waste recycling company in Ahmedabad that facilitates the safe disposal of E-waste products while offering uncompromised recycling services for environmental and social advantages.",
];

export const rubberWaste = [
  "More than 270 rubber tyres are discarded every year. Tyres are just one of the many applications of rubber. Much of which ultimately ends up in landfills. At Recycling Hub, we have a zero-waste-to-landfill policy, which means we prevent waste from getting disposed of in landfills wherever possible, including rubber waste.",
  "We collect 100% rubber waste and recycle it. We use a wide range of products to ensure that your rubber waste is handled with full compliance and using the latest environmental regulations. As GPCB authorized recyclers, we follow the entire process within the enclosed environment and prevent the release of toxic gases.",
];

export const woodenScrapBuyer = [
  "Recycling Hub stands as the foremost wooden scrap buyer in Ahmedabad, providing top-notch recycling services that contribute to sustainable practices and environmental preservation. With years of experience and a commitment to eco-friendly operations.",
  "Recycling Hub has established itself as a trusted partner for individuals and businesses looking to dispose of wooden scrap responsibly.",
];

export const woodenPalletsScrapBuyer = [
  "Recycling Hub has established itself as the premier wooden pallets scrap buyer in Ahmedabad. known for its commitment to sustainability and excellence in service. As a trusted name in the industry, Recycling Hub plays a pivotal role in the responsible disposal and recycling of wooden pallets, contributing to the conservation of natural resources and the reduction of environmental waste.",
  "Wooden pallets are essential for the transportation and storage of goods across various industries. However, once they reach the end of their life cycle, they can become a significant source of waste. Recycling Hub steps in to ensure that these pallets are not discarded irresponsibly but are instead repurposed or recycled in an environmentally friendly manner.",
];

// * Service Grid

export const services = [
  {
    title: "End-to-End Hazardous Waste Management",
    description:
      "We help our clients throughout all the hazardous waste management phases, including logistics, training, and management of transboundary movement permits.",
  },
  {
    title: "Comprehensive Waste Management",
    description:
      "We are a GPCB authorized decontamination service provider in Gujarat, offering the safest and most transparent hazardous waste treatment with accurate reports.",
  },
  {
    title: "Maximum Pollution Reduction",
    description:
      "We work to reduce all solid, liquid and gaseous industrial emissions and offer the best technical solution in pollution control, management and facility operations.",
  },
  {
    title: "Customized Waste Solutions",
    description:
      "We create dedicated waste recycling solutions based on your needs. As a GPCB authorized recycler, we tackle pollution generated through hazardous waste recycling.",
  },
];

export const plasticServices = [
  {
    title: "Circular Economy",
    description:
      "Plastic waste can take as much as 1000 years to decompose. The solution is recycling to recreate purposeful products out of plastic. Our team actively works towards meeting the circular economy needs of our clients.",
  },
  {
    title: "Extended Producer Responsibility",
    description:
      "We engage 1000+ saffai sathis to collect millions of metric tons of post-consumer plastic waste from different sources and divert them towards recycling. We also help corporates in meeting their EPR & PWM compliances.",
  },
  {
    title: "Audit & Consultation",
    description:
      "We provide the best auditing and consulting in compliance with the law related to resource recovery, circular economy, reverse logistics and other waste handling solutions. Strategize your waste management with us.",
  },
  {
    title: "Waste Management Services",
    description:
      "We are the best GPCB authorized plastic waste recycler in Gujarat, responsible for managing sustainable waste management solutions for bulk waste generators, be it businesses, industries or government entities.",
  },
];

export const industrialServices = [
  {
    title: "Disposal",
    description:
      "#ZeroWasteToLandfills is what we pledge. Therefore, we at SV Green deploy the safest and eco-friendly methods for disposal that lead to recycling and recreation.",
  },
  {
    title: "Logistics",
    description:
      "When we say end-to-end waste management, we mean it quite literally! Collection, transportation, sorting, bulking and recycling we manage it all.",
  },
  {
    title: "Sourcing",
    description: "Recyclables and other reuses of materials.",
  },
  {
    title: "Management",
    description:
      "At SV Green, different types of wastes are treated differently to ensure safety, accuracy and compliance with regulatory guidelines.",
  },
  {
    title: "Reporting",
    description:
      "We keep you notified with digital receipts of the processes so that you are informed at every stage. We also provide monthly reports for overall analysis.",
  },
  {
    title: "Diversion Certificate",
    description:
      "We provide a “Waste Diversion Certificate” with the environmental footprint report so that you can achieve your compliance goals.",
  },
];

export const eprServices = [
  {
    title: "Waste Reporting",
    description:
      "We have embraced IoT technology to monitor the collection and disposal of plastic waste while updating you digitally.",
  },
  {
    title: "Expert Assistance",
    description:
      "Our well-trained and equipped team provides you with quality services. Our engineers and lawyers assist you in meeting compliance.",
  },
  {
    title: "Measuring Impact",
    description:
      "We understand your dire need for compliance. Hence, we provide a social & environmental impact report every quarter along with the EPR quarterly report.",
  },
  {
    title: "Plastic Waste Stream",
    description:
      "We collaborate with different waste streams to collect PET, MLP, HDPE, LDPE & PP, and other plastic waste for recycling and safe disposal.",
  },
];

export const circularEconomyServices = [
  {
    title: "Economic Benefits",
    description:
      "Along with the environmental benefits, a circular economy for plastic offers significant long-term economic benefits. Some of these benefits may be indirect but impact the global value chains.",
  },
  {
    title: "Enviromental Benefits",
    description:
      "The circular economy can cut greenhouse gas emissions by 39%. It also bolsters biodiversity, which is threatened due to rising pollution levels.",
  },
  {
    title: "System Benefits",
    description:
      "It results in a reduction of primary material consumption in higher production by enhancing the system's value. Additionally, it creates businesses at a lower cost by creating new profit streams.",
  },
  {
    title: "Company Benefits",
    description:
      "Lower the cost of the businesses by creating new profit streams. Also, analyze complex medium-lived products that fast move consumer goods while showing a circular Economy with various improvements.",
  },
];

export const organicWasteServices = [
  {
    title: "More Sanitary than Traditional Waste",
    description:
      "For food industries, leftovers are a significant cause of attraction for pests, rats, rodents, dogs, and other infestations, causing product damage and contamination. Safe disposal of food waste is essential for appropriate sanitation. Recycling hub is a responsible organic recycler helping effective food waste management.",
  },
  {
    title: "Turn Waste into Resources",
    description:
      "Organic waste can be used as manure to nourish the soil and further reinforce the green revolution. Waste food dumped in the landfills rots over time and produces harmful methane gas during decomposition. We buy organic scrap and manage it safely and effectively as per governmental guidelines.",
  },
  {
    title: "Makes Sound Financial Sense",
    description:
      "Various city waste managers are given charge of trash and other waste diversions. One indeed considers raising the dumping by finding new areas and unearthing the purpose of disposal. If you're looking to trim your excess expenditure, consider Recycling Hub for the financial benefits.",
  },
  {
    title: "Sustains Communities",
    description:
      "We support local farmers by providing adequately recycled organic manure to make the soil more fertile. In turn, we encourage organic farming for better human health. Choose Recycling Hub to get outstanding waste management service for all types of waste, including organic waste.",
  },
];

export const eWasteServices = [
  {
    title: "Conserves Natural Resources",
    description:
      "E-waste recycling also improves the availability of raw materials. You can reuse metal and parts or entire parts such as motherboards. ICs can also be extracted for refurbishing, reducing costs for companies.",
  },
  {
    title: "Reflect Business Credibility",
    description:
      "Recycling is a concrete approach to demonstrating a company's dedication to social virtues. We provide recycling certifications that reflect your efforts and how your company is meeting its green aspirations.",
  },
  {
    title: "Supports the Community",
    description:
      "Donate your old waste products such as computers and mobile phones that create a monetary return. As an E-waste recycler in Gujarat, our team helps individuals gain access to technology with ease.",
  },
  {
    title: "Protects health & environment",
    description:
      "Electronics come with hazardous material that's harmful to the environment. Therefore, we allow the customer to reuse and recycle electronics by keeping hazardous material from harming humans.",
  },
];

export const rubberWasteServices = [
  {
    title: "Conserve Landfill Space",
    description:
      "Tyres take up a lot of space in landfills due to their shape, size and quantity. As landfill is a finite space, it mandates reducing the dumping of oversized bulky items that take up more space than necessary. At Recycling hub, we provide quality recycling service with the best sustainable waste management solutions.",
  },
  {
    title: "Create Beneficial Products",
    description:
      "Recycled tyres are used in several ways. It helps generate fuel, rubberized asphalt, railroad ties, flooring, and other alternatives. We at Recycling hub are authorized scrap tyre buyers in Ahmedabad to offer transparent services.",
  },
  {
    title: "Prevents The Spread Of Disease",
    description:
      "The old tyres attract disease-carrying rodents. It provides a breeding ground for mosquitoes that carry lethal diseases. We are the best waste management company in Ahmedabad that eliminates tyre waste and helps prevent disease spread.",
  },
  {
    title: "Produce Useful Raw Materials",
    description:
      "The waste tyre, when recycled, produces secondary raw materials. The rubber, after recycling, is superior to traditional materials like sound absorption, lightweight, insulting, crack-resistant, etc. We are GPCB authorized recyclers to offer effective waste management.",
  },
];

export const woodenScrapBuyerServices = [
  {
    title: "Reuse",
    description:
      "Pallets are very easy to repair and can be reused from time to time. Demolished old fences and cabins can also be reused for new projects. We are the best wooden pallets buyer in Gujarat.",
  },
  {
    title: "Recycle",
    description:
      "When one cannot use the original form of pallet, it is sent for the recycling process, which can be used for fences, barriers, bridges, or to control erosion. We ensure appropriate recycling for each.",
  },
  {
    title: "Processing bulk",
    description:
      "A vast amount of pallets are produced by industries. Earlier, the waste ended up in landfills which we, as wood waste recyclers, attempt to prevent.",
  },
  {
    title: "Biomass",
    description:
      "It is one of the best energy sources that produce electricity or steam using wood. It is the best waste management solution nowadays.",
  },
];

export const woodenPalletsScrapBuyerServices = [
  {
    title: "Reuse",
    description:
      "Pallets are very easy to repair and can be reused from time to time. Demolished old fences and cabins can also be reused for new projects. We are the best wooden pallets buyer in Gujarat.",
  },
  {
    title: "Recycling",
    description:
      "When one cannot use the original form of pallet, it is sent for the recycling process, which can be used for fences, barriers, bridges, or to control erosion. We ensure appropriate recycling for each.",
  },
  {
    title: "Processing bulk",
    description:
      "A vast amount of pallets are produced by industries. Earlier, the waste ended up in landfills which we, as wood waste recyclers, attempt to prevent.",
  },
  {
    title: "Biomass",
    description:
      "It is one of the best energy sources that produce electricity or steam using wood. It is the best waste management solution nowadays.",
  },
];

// * Expertise section

export const expertise = [
  "Hazardous Waste Profiling",
  "Hazardous Waste Collection",
  "Hazardous Waste Treatment and Recycling",
  "Online access to account and waste information",
  "Analysing Hazardous waste removal",
];

export const PlasticWasteServices = [
  "Reduced environmental pollution",
  "Ensure 100% compliance as per PCB norms",
  "Get quick approval for PWM registration",
  "Get support for circular economy",
  "Create sustainable employment for local rag pickers",
  "Get waste diversion certificate",
  "Online Manifest for plastic waste recycling",
];

export const IndustrialWasteServices = [
  "Reduced environmental pollution",
  "Environmental and Economic Sustainability",
  "Ensure 100% compliance as per PCB norms",
  "Get quick approval for PWM registration",
  "Get support for circular economy",
  "Create sustainable employment for local rag pickers",
  "Get waste diversion certificate",
];

export const EPRServices = [
  "SBM Approved EPR Agency",
  "End to End Responsibility",
  "Significant Social Impact",
  "Transparency In Reporting",
];

export const circularEconomyService = [
  "Improved Technologies",
  "Composting Facilities",
  "Enviromental Benefits",
  "Save More",
  "Recycled Goods",
  "Highly Experienced Team",
];

export const rubberWasteService = [
  "Preserve the Environment",
  "Reduce illegal dumping",
  "Integrity",
  "Multiple Rubber Uses",
  "Transparency",
  "Inclusion",
];

export const woodenScrapBuyerService = [
  "Conserve natural resources",
  "Keep landfills from growing",
  "Saves energy",
  "Reduce green-house gas emissions",
  "Supports job growth",
  "Supports circular economy",
];

export const woodenPalletsScrapBuyerService = [
  "Conserve natural resources",
  "Keep landfills from growing",
  "Saves energy",
  "Reduce green-house gas emissions",
  "Supports job growth",
  "Supports circular economy",
];

// * Benefits Stepper

export const benefits = [
  {
    title: "Excellent Service",
    description:
      "We are here to take the weight off your shoulders by providing at par hazardous waste management services.",
  },
  {
    title: "Value Addition",
    description:
      "We provide excellent prices and even more incredible value addition to our clients. We adhere to safety protocols for hazardous management.",
  },
  {
    title: "Compliance & Service",
    description:
      "Known for compliance in the hazardous waste management business, we keep you fully compliant with all.",
  },
  {
    title: "Speed & Timeliness",
    description:
      "Timely collection, processing and reporting of our services and processes are what we follow at SV Green.",
  },
  {
    title: "Safety Measures",
    description:
      "We take care of safety first. We take proper precautions to protect the environment, equipment and facilities.",
  },
  {
    title: "Document Retention",
    description:
      "We have copies of your profiles, certificates of destruction, manifests, and other documents that we retain for futuristic retrieval needs.",
  },
];

export const PlasticWasteProcess = [
  {
    title: "Collection",
    description:
      "We collect plastic waste from bulk waste generators and from households in association with the urban local bodies. Collections are done by our trained staff along with the engagement of the local safai sathis. All the collected plastic waste comes to our factory for further segregation.",
  },
  {
    title: "Sorting",
    description:
      "In the sorting process, we separate the mixed plastic waste into different  types of plastic. It is done by our specialized team using appropriate tools and mechanical machinery. By manual sorting, we segregate different kinds of plastic waste and place them in the respective categories of plastic ensuring proper next level processing. ",
  },
  {
    title: "Size Reduction",
    description:
      "Plastic waste comes in different sizes and shapes. Using a machine like a crusher and a shredder, we reduce the materials size and make them suitable for recycling processes. As a leading waste management company, we ensure to provide a smooth and constant flow of the plastic waste management cycle.",
  },
  {
    title: "Recycling",
    description:
      "Plastic waste comes in different sizes and shapes. Using a machine like a crusher and a shredder, we reduce the materials’ size and make them suitable for recycling processes. As a leading waste management company, we ensure to provide a smooth and constant flow of the plastic waste management cycle. ",
  },
];

export const IndustrialWasteProcess = [
  {
    title: "Technology-Driven Process",
    description:
      "Leverage technology-driven accurate disposal solutions to manage your waste and recycling streams at Gujarat's leading industrial waste management company",
  },
  {
    title: "Addressing environmental concerns",
    description:
      "As an industrial waste recycler, we use advanced disposal methods which eliminate the impact on environmental concerns with recycling waste diversion solutions.",
  },
  {
    title: "Improved Waste Flow Efficiencies",
    description:
      "At SV Green, you get a continual site and waste stream analysis with continuous improvement metrics to keep costs in line.",
  },
  {
    title: "Compliance Management And Regulatory",
    description:
      "We know how crucial regulatory compliance is. Hence, we ensure 100% compliance for all our waste management solutions.",
  },
  {
    title: "Save Environment And Money",
    description:
      "Now leave green footprints and cost checked with SV Green's affordable industrial waste management solutions.  ",
  },
];

export const EPRProcess = [
  {
    title: "Reverse Logistics",
    description:
      "SV Green is a preferred GPCB authorized scrap buyer in Gujarat with a well-structured reverse supply chain. We ensure effective plastic waste collection and allow adequate transportation of post-consumer waste to various predetermined destinations.",
  },
  {
    title: "Social Inclusion",
    description:
      "At SV Green, we empower our associate safai saathis by generating earning sources for a decent living. We offer the same empathetic care to every member internal and external to the company as the best GPCB approved EPR agency in Gujarat.",
  },
  {
    title: "Public Awareness",
    description:
      "Awareness is the key to bringing about a change. Hence, we conduct extensive awareness programs that include corporate events, collection drives, and other social media campaigns on source segregation and the impact of plastic pollution.",
  },
];

export const circularEconomyProcess = [
  {
    title: "Waste And Pollution Reduction",
    description:
      "A Circular economy designs a reduction of negative impacts of waste disposal, which cause damage to natural systems. The design includes the release of greenhouse gases, air pollution, and other hazardous substances. We are GPCB authorized scrap buyers to collect waste and recycle it for further usage while employing circular economy principles. ",
  },
  {
    title: "Keep Products And Materials In Use",
    description:
      "The Circular Economy preserves value in the form of energy, materials, and labor. One can design reusability, durability, remanufacturing, and recycling products and materials. A circular system makes effective use of bio-based materials that encourage different services. We are GPCB authorized recyclers to help you get rid of contaminations.",
  },
  {
    title: "Regenerate Natural Systems",
    description:
      "A circular user economy usually avoids using non-renewable resources and helps preserve renewable ones. For instance, we return valuable nutrients to the soil with supporting regeneration. We use renewable energy and rely on fossil fuels while undergoing the best recycling solutions.",
  },
];

export const organicWasteProcess = [
  {
    title: "Collection",
    description:
      "The first step is to collect the waste material from producers. We ensure uninterrupted waste collection from the site so that your operations may continue uninterrupted. Our workforce is trained to execute professional services with appropriate safety measures.",
  },
  {
    title: "Inert Separation",
    description:
      "It is one of the essential steps where organic waste is recycled using the inert separation technique. In this phase, waste accumulated at our facilities is segregated manually using machinery that removes substances like glass, plastic, and bricks and separates the materials.",
  },
  {
    title: "Preparation",
    description:
      "Before the organic waste is added to a recycling system, we need to prepare it first. Composting, shredding, and stacking organic waste is a must. There are a few methods used, like stabilization before recycling. You can rely on us for responsible disposal of your organic waste.",
  },
  {
    title: "Recycling Process",
    description:
      "Understanding the nature of organic waste and its desired end products, we adopt a suitable method for recycling. As a GPCB authorized recycler, we help you eliminate all waste and treat them well using thermophilic digesters.",
  },
  {
    title: "Screening and Grading",
    description:
      "In this phase, the compost is screened into different sizes and used for other purposes. Depending on the application of end products, screening and grading are an essential part of the organic waste management process.",
  },
];

export const eWasteProcess = [
  {
    title: "Dismantling",
    description:
      "As the name suggests, this stage involves breaking down the E-waste into smaller components to avoid dilution or contamination. It is done carefully to prevent any toxic substance from getting into the downstream processes.",
  },
  {
    title: "Processing",
    description:
      "It's a stage where industries use the e-waste process for scaling large operations and obtaining concentrated recyclable materials. We have separate units for crushing, eddy current, shredders, and other air separators.",
  },
  {
    title: "Refining",
    description:
      "It's a process of refining raw materials separated from dismantling and processing with minimal to no environmental impact. It comes with most fractions needed for disposal as secondary raw material and in the final disposal site.",
  },
];

export const rubberWasteProcess = [
  {
    title: "Storage Of Waste",
    description:
      "After being removed, ELT (End of Life Tyre) are collected in the center for controlling, weighing, and later stored before being taken to plants for treatment.",
  },
  {
    title: "First Shredding",
    description:
      "ELT is cut into shreds sized between 5 to 40 cm in the first step. Later it is sent for energy recovery of future shredded materials to allow the separation of materials.",
  },
  {
    title: "Second Shredding",
    description:
      "In the next level, smaller pieces are cut until it's possible to separate the rubber from steel and textile fibers. Later rubber is treated to obtain granules and powder for new product creation.",
  },
  {
    title: "Recovery Of Materials",
    description:
      "The materials are the output of various types and dimensions based on typology in the final process. Therefore, we process it accordingly.",
  },
];

export const woodenScrapBuyerProcess = [
  {
    title: "Environmental Impact",
    description:
      "Preventing deforestation is one of the most essential and first benefits of wood recycling. Industries must follow precisely the waste management system to avail for a better tomorrow.",
  },
  {
    title: "Reduction of energy costs",
    description:
      "It is the best source of recycling to reduce energy costs. When products are made from solid waste, energy is expended to extract and process the materials that include burning fossil fuels.",
  },
  {
    title: "Reduce risk to fire",
    description:
      "We find accumulated heaps of wood waste close to work premises. To prevent such circumstances, our team helps you gather wood waste and contact a professional recycling facility instead.",
  },
  {
    title: "New and better opportunities",
    description:
      "It gives numerous opportunities that keep up with evolving customer demand for recycled products. It also includes industrial wood stock.",
  },
];

// * why recycle
export const whyRecycle = [
  {
    title: "Technology Driven Service",
    Icon: PiNuclearPlantLight,
  },
  {
    title: "Present in Wide Range of Cities",
    Icon: PiCity,
  },
  {
    title: "Integrity and Work Ethics",
    Icon: GoLaw,
  },
  {
    title: "Excellent Service",
    Icon: RiServiceLine,
  },
  {
    title: "Excellent Service",
    Icon: GiTeamIdea,
  },
  {
    title: "Waste Management Solution",
    Icon: FaRecycle,
  },
];
