import { PiNuclearPlantLight, PiCity } from "react-icons/pi";
import { GoLaw } from "react-icons/go";
import { RiServiceLine } from "react-icons/ri";
import { GiTeamIdea } from "react-icons/gi";
import { FaRecycle } from "react-icons/fa";

export type NavItem = {
  name: string;
  href?: string;
  children?: Array<{ name: string; href: string }>;
};

export const PHONE_NUMBER = ""; // e.g. "+1-555-123-4567" (set to show Call button)

export const NavItems: NavItem[] = [
  { name: "Home", href: "/" },
  { name: "About us", href: "/about-us" },
  {
    name: "Services",
    href: "/services",
    children: [
      {
        name: "Hazardous waste management",
        href: "/services/hazardous-waste-management",
      },
      {
        name: "Plastic waste management",
        href: "/services/plastic-waste-management",
      },
      {
        name: "Industrial waste management",
        href: "/services/industrial-waste-management",
      },
      {
        name: "Extended producer responsibility",
        href: "/services/extended-producer-responsibility",
      },
      { name: "Circular economy", href: "/services/circular-economy" },
      {
        name: "Organic waste management",
        href: "/services/organic-waste-management",
      },
      {
        name: "E-waste management services",
        href: "/services/e-waste-management",
      },
      {
        name: "Rubber scrap waste management",
        href: "/services/rubber-scrap-waste-management",
      },
      { name: "Wooden scrap buyer", href: "/services/wooden-scrap-buyer" },
      {
        name: "Wooden Pallets scrap buyer",
        href: "/services/wooden-pallets-scrap-buyer",
      },
    ],
  },
  { name: "Blog", href: "/blog" },
  { name: "FAQs", href: "/faqs" },
  { name: "Contact us", href: "/contact-us" },
];

// * Content with image
export const hazardContent = [
  "Waste that is harmful to human health and the environment is classified as hazardous. We are a reliable hazardous waste recycler in Ahmedabad, Gujarat, extending an efficacious treatment process that aligns with your industrial waste handling needs.",
  "Recycling Hub is a GPCB approved hazardous waste recycler in Ahmedabad that has earned the stature of the most trusted, owing to our unparalleled services and a well-trained team.",
  "We take time to understand the requirement of businesses, industrial behemoths and government agencies to cater to their distinctive needs. Furthermore, we take responsibility for your hazardous waste from collection to recycling.",
  "As a Hazardous waste management company in Gujarat, we offer a complete range of environmental services, including waste collection, recycling compliances, EHS inspections, and other internal waste management services.",
  "With our regulatory compliance for hazardous waste, you can rest assured of the safety of humans, infrastructure, and the environment.",
];

export const plasticWasteContent = [
  "According to Central Pollution Control Board, in 2019-20, approximately 34,69,780 TPA of plastic waste was generated by 35 states/UTs of India. The figures are alarming and impose a need for plastic waste management. Hence, we step in as a GPCB a GPCB authorized plastic waste recycler in Gujarat.",
  "At Recycling Hub, environment protection is the motto that leads us to deliver top-notch services. Being a plastic waste management company in Ahmedabad",
  "We formulate customized plans for our clients as we understand the distinctive needs of various industries. Furthermore, as a GPCB approved waste recycler, we adhere to regulatory guidelines, so you get 100% compliance, justified pricing and unparalleled services.",
  "Our plastic waste collection activity is undertaken by a well-trained team of people from marginalised sectors that follow stringent safety protocols to ensure seamless service. Additionally, our plastic waste recycling units comply with PCB guidelines so that you can rely on us for quality and accurate services.",
];

export const industrialWasteContent = [
  "Industrial and manufacturing processes generate tons of waste at every stage. The nature of the waste depends on the type of process governed by strict regulations, for instance, hazardous waste. Hence, as Gujarat's one-stop industrial waste management company, we provide comprehensive and strategic solutions.",
  "Being a GPCB authorized industrial waste recycler, we are your perfect ally for recycling, diversions and other purposeful reuse of your waste. Recycling Hub is a leading industrial scrap buyer in Gujarat to provide all-inclusive waste management and disposal services.",
  "Our expert team understands the chemical, materials, and products with proficient knowledge concerning CPCB & GPCB guidelines. Our industrial waste management services vouch for 100% compliance like no other. Being an industrial waste recycling company , we tend to relieve the hassles of waste management.",
];

// * Benefits Stepper

export const benefits = [
  {
    title: "Excellent Service",
    description:
      "We are here to take the weight off your shoulders by providing at par hazardous waste management services.",
  },
  {
    title: "Value Addition",
    description:
      "We provide excellent prices and even more incredible value addition to our clients. We adhere to safety protocols for hazardous management.",
  },
  {
    title: "Compliance & Service",
    description:
      "Known for compliance in the hazardous waste management business, we keep you fully compliant with all.",
  },
  {
    title: "Speed & Timeliness",
    description:
      "Timely collection, processing and reporting of our services and processes are what we follow at Recycling Hub.",
  },
  {
    title: "Safety Measures",
    description:
      "We take care of safety first. We take proper precautions to protect the environment, equipment and facilities.",
  },
  {
    title: "Document Retention",
    description:
      "We have copies of your profiles, certificates of destruction, manifests, and other documents that we retain for futuristic retrieval needs.",
  },
];

export const PlasticWasteProcess = [
  {
    title: "Collection",
    description:
      "We collect plastic waste from bulk waste generators and from households in association with the urban local bodies. Collections are done by our trained staff along with the engagement of the local safai sathis. All the collected plastic waste comes to our factory for further segregation.",
  },
  {
    title: "Sorting",
    description:
      "In the sorting process, we separate the mixed plastic waste into different  types of plastic. It is done by our specialized team using appropriate tools and mechanical machinery. By manual sorting, we segregate different kinds of plastic waste and place them in the respective categories of plastic ensuring proper next level processing. ",
  },
  {
    title: "Size Reduction",
    description:
      "Plastic waste comes in different sizes and shapes. Using a machine like a crusher and a shredder, we reduce the materials size and make them suitable for recycling processes. As a leading waste management company, we ensure to provide a smooth and constant flow of the plastic waste management cycle.",
  },
  {
    title: "Recycling",
    description:
      "Plastic waste comes in different sizes and shapes. Using a machine like a crusher and a shredder, we reduce the materials’ size and make them suitable for recycling processes. As a leading waste management company, we ensure to provide a smooth and constant flow of the plastic waste management cycle. ",
  },
];

export const IndustrialWasteProcess = [
  {
    title: "Technology-Driven Process",
    description:
      "Leverage technology-driven accurate disposal solutions to manage your waste and recycling streams at Gujarat's leading industrial waste management company",
  },
  {
    title: "Addressing environmental concerns",
    description:
      "As an industrial waste recycler, we use advanced disposal methods which eliminate the impact on environmental concerns with recycling waste diversion solutions.",
  },
  {
    title: "Improved Waste Flow Efficiencies",
    description:
      "At Recycling Hub, you get a continual site and waste stream analysis with continuous improvement metrics to keep costs in line.",
  },
  {
    title: "Compliance Management And Regulatory",
    description:
      "We know how crucial regulatory compliance is. Hence, we ensure 100% compliance for all our waste management solutions.",
  },
  {
    title: "Save Environment And Money",
    description:
      "Now leave green footprints and cost checked with Recycling Hub's affordable industrial waste management solutions.  ",
  },
];

// * Expertise section

export const expertise = [
  "Hazardous Waste Profiling",
  "Hazardous Waste Collection",
  "Hazardous Waste Treatment and Recycling",
  "Online access to account and waste information",
  "Analysing Hazardous waste removal",
];

export const PlasticWasteServices = [
  "Reduced environmental pollution",
  "Ensure 100% compliance as per PCB norms",
  "Get quick approval for PWM registration",
  "Get support for circular economy",
  "Create sustainable employment for local rag pickers",
  "Get waste diversion certificate",
  "Online Manifest for plastic waste recycling",
];

export const IndustrialWasteServices = [
  "Reduced environmental pollution",
  "Environmental and Economic Sustainability",
  "Ensure 100% compliance as per PCB norms",
  "Get quick approval for PWM registration",
  "Get support for circular economy",
  "Create sustainable employment for local rag pickers",
  "Get waste diversion certificate",
];

// * Service Grid

export const services = [
  {
    title: "End-to-End Hazardous Waste Management",
    description:
      "We help our clients throughout all the hazardous waste management phases, including logistics, training, and management of transboundary movement permits.",
  },
  {
    title: "Comprehensive Waste Management",
    description:
      "We are a GPCB authorized decontamination service provider in Gujarat, offering the safest and most transparent hazardous waste treatment with accurate reports.",
  },
  {
    title: "Maximum Pollution Reduction",
    description:
      "We work to reduce all solid, liquid and gaseous industrial emissions and offer the best technical solution in pollution control, management and facility operations.",
  },
  {
    title: "Customized Waste Solutions",
    description:
      "We create dedicated waste recycling solutions based on your needs. As a GPCB authorized recycler, we tackle pollution generated through hazardous waste recycling.",
  },
];

export const plasticServices = [
  {
    title: "Circular Economy",
    description:
      "Plastic waste can take as much as 1000 years to decompose. The solution is recycling to recreate purposeful products out of plastic. Our team actively works towards meeting the circular economy needs of our clients.",
  },
  {
    title: "Extended Producer Responsibility",
    description:
      "We engage 1000+ saffai sathis to collect millions of metric tons of post-consumer plastic waste from different sources and divert them towards recycling. We also help corporates in meeting their EPR & PWM compliances.",
  },
  {
    title: "Audit & Consultation",
    description:
      "We provide the best auditing and consulting in compliance with the law related to resource recovery, circular economy, reverse logistics and other waste handling solutions. Strategize your waste management with us.",
  },
  {
    title: "Waste Management Services",
    description:
      "We are the best GPCB authorized plastic waste recycler in Gujarat, responsible for managing sustainable waste management solutions for bulk waste generators, be it businesses, industries or government entities.",
  },
];

export const industrialServices = [
  {
    title: "Disposal",
    description:
      "#ZeroWasteToLandfills is what we pledge. Therefore, we at Recycling Hub deploy the safest and eco-friendly methods for disposal that lead to recycling and recreation.",
  },
  {
    title: "Logistics",
    description:
      "When we say end-to-end waste management, we mean it quite literally! Collection, transportation, sorting, bulking and recycling we manage it all.",
  },
  {
    title: "Sourcing",
    description: "Recyclables and other reuses of materials.",
  },
  {
    title: "Management",
    description:
      "At Recycling Hub, different types of wastes are treated differently to ensure safety, accuracy and compliance with regulatory guidelines.",
  },
  {
    title: "Reporting",
    description:
      "We keep you notified with digital receipts of the processes so that you are informed at every stage. We also provide monthly reports for overall analysis.",
  },
  {
    title: "Diversion Certificate",
    description:
      "We provide a “Waste Diversion Certificate” with the environmental footprint report so that you can achieve your compliance goals.",
  },
];

export const whyRecycle = [
  {
    title: "Technology Driven Service",
    Icon: PiNuclearPlantLight,
  },
  {
    title: "Present in Wide Range of Cities",
    Icon: PiCity,
  },
  {
    title: "Integrity and Work Ethics",
    Icon: GoLaw,
  },
  {
    title: "Excellent Service",
    Icon: RiServiceLine,
  },
  {
    title: "Excellent Service",
    Icon: GiTeamIdea,
  },
  {
    title: "Waste Management Solution",
    Icon: FaRecycle,
  },
];
